notifications:
  email:
    on_success: never
    on_failure: always

language: node_js
node_js:
  - 8

install:
  - npm install

cache:
  directories:
    - "node_modules"

script:
  - npm test

after_success:
  - npm run build

deploy:
  local-dir: dist
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  fqdn: aikaka.net
  on:
    branch: master
